apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/visnja/argoflow.git
    targetRevision: 123456789012/cluster.master-cat.com
    path: distribution/mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
