apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
    - grafana.my-cluster.master-cat.com
    - kiali.my-cluster.master-cat.com
    - kubecost.my-cluster.master-cat.com
