kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-postgresql
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-postgresql
      namespace: auth
      creationTimestamp: null
    data: null
  encryptedData:
    postgresql-password: AgBUXNUpdkcr/llgcmcTyxDreFRYWjllQCdDGa0YXQ/x7WVCl7zH1fO7gFiZ+rLgaUINdAylbuN1gKRmvUqELHj0pPmy6av6ZZntuO8213RwsobtvcWbMAE+Ayc7mDJVY0WHLfuXJTMZ3u5AIkQrO5AbCiS0pcIcjW7GngJlJSXpcs3Kxf4afpeRU1lMpSMx9+Opzctdf39WPeuD4LajFNSh+8HY2iHw1AgLfKD6KUxda/MxLXNTSNxUlFT00VpyIJPB+zuLYiCQSxgqjLTQGIxTAYkO0JaTcIo7/rQPeK0KZ/Hg/D3RGEV+Dcs+nWs+e4KhYEeAlBsOB19oqYCVx0dq+uIf5QJr0SeNKyJR9DXyyjGfyg54HyLiz8TGPdpYLtp48uFixu7VLsP2MA2a1E1nLafktNavqzPzVyMRyxlrnZ4oVT1AToRyj/muCdJS+qfrjMZfoXL0+M97zWm+zGRAb1Z834lDqexr5Zl27C/5Af/G4lFwtQT+oAZYgOV16J66+cvEMVVE8Y6QVnqMwAKf0fauVaRsXrccAvoP6Ln/MfqPd8tEADTGd1LcDWlgo7Igjc2PaiSqd3iuil8z16cvVYOVwJClMeaEPBmKLoVhwy3zZtDhfdnTtZddGWCL+Zoc9px/Gq8jt+rlIU5mMco/mKeaFHLPKgMajU7VvswadpnqbNIlD3Oh/j/4Tby8q/rp4Tcwnr9o1P/SZ0LY/HY8m3f40TR4Zau3DFfnpupG2Q==
    postgresql-postgres-password: AgCYCrxzLZHSZeDZgVOKliZGLreNIZImGeeDb0N/fOsyus0Vvl1ztCLteUhNeRx7/u+/ljKwBaBnMisfbuHLbXdXbcSIYsNdUPyg8Bl7AmnP8X4BtPc+XY0znVbtEVaGmVfsi3AzMn8je2glSRk7oNLfYUw0B+NzNAM5rfD7o7dES+1At9M9Lvy3OJ3GAmDwYrpzHjGb6LPK/x2CVpx/PvrbdR+Yc2XMFnuCm/rpP0KpXuKLpjdhWu97fGpptCUvFrcs2APM97/ljiw3kS7HjPiWPycet9Aq4o4gqGk45Ka/MeXUhITkgILjke+hTBACj3hGuusnFhW2snA1GLw32s91bJy65h+RtMJeebaOdllFvQv7OVKaantk7M3paXloZrlPVi5MG23Rlwa7iqfMPigqfFirTgvhz16ofVj12hprq+tGtQoIYHJowGF5aAufXraJjRK0W0A0Y2ve/3+IsmVGXk3JRSeJAU09tq9qpJfUOXmNqK+aMAUahihJ4mtZ9AWiPgha+MiAaPkm83h5R4LLeFKoRPVe0zkrNrccQHauoVUtaEzHEL7NGYQz+8LzbsYU2WeXbTN/23+efXmu3h82zVTjPODLKWbQEsKCFYIH76Jy0QIyCtLjJbv9vx7ss4d409fsFf/y258o2hQ5hyAiQCBqgwLLHxG+soPna+V9JYwAngXXlpqMmfxOPuGFauRkMeE5HPPQ9NMRQZo1tN2o22ZdvQhd2br5+cC7mQMgeA==
