kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgALv23qAxCNSJckSiVxjI/rqamidTkUdIyTLMdrOEslMM7eIaV86w3MD3Mc/y0mP0PpcAWkiF4AyDlFD6ifv4wgUiyWL80m71UcyFDR9EaLEtWQkIuX/tfgw83Gp6WweiD7qWegIOJiSlstFx76p/ziM74Tz8mepN4g57PhQ0uxUjg+QRD+1MWZ+c98acM4xoKdpBLoaLkBzJlGVfNzsUro3P9nWs5zajTR2yHpthvLlt67HMzh4IyVvciC16JNAFASDxu+ZEsvV7Cxq9soHEmcSexOra2mZN5vJk8bn2soP+I4u++RGW8CH8fEHenOClJOZ0YygPiNoERuPctB3UXNFKpcIqxoJ+ZK03+cdK5Pv9LxPFVNsGAvZPcgf/nY81i/zh/waPVYKK0LZHB7pzSjO2BBlGJySkxvjxRKwf6OGNhhTYvs3tSAG+7+fgEP2so4ExVsLL+Mk/d7rKVs6dnpwjaxHPaANpIUqJ4tHa4lOB3PwqLVvnxAnztDSkojm2D4d3g7nLWpNfCznbn1OcEs2J7jSHWPWSqWSpujTE6MqI2SChyAj2bh6cHN19I9Y+NItdfNHHt0hZAv2s8gz+DgU9a/QbzDqpVuDlGHrpf7zsQhh3sJUgc6am5+N0Zuad4Z+V2b5lhDB5XR9NdYdGgLXLj4TfwKI1ABotni3bAPanAbZIFAZ4HlZTHVY7+0q1I3YEKtmJ6aENlwylE=
    admin-user: AgB3dbwXCjoNq+INCYL9cYI9GcGk80CkiGdyJH5NmFW9xCBzRDcLqE4qzKMHHyfKfBSi7DYHVYtvJv0G/kTSJ3ASayR4pNcKl7f8VZYtR9hVpfIWctXECySjrGcBsgC/KhX2BeGI3vHHC3hFLFYMrsA1apSl0/mXTumiVyJad1WwhdvIPrOW9OGz9XOBm+OZ7zxtiOar0fqXNn9BhkS+xX6SNCQN/M5oNuS9DPCLco1cEl8HXDK9w9Zvcflqj85Xtl24ZK2XJmkCYKBqCOYxbIbVDWCtDnhH9FM2Rmy9HjHry0mgaGEFSdrbD3Yi4xVfT7BJvXliCvXOHAHjHtgKKDr3zEIwRUXnZXODytj9eRvo9Mv6I80rK372jyAeK95JQamp+VHk1uRGjqFAb+Typ1ZkCjru2DZeCdn2BbG6LmxZhyk0rGVSiILYnEhMOKQ2bWaP8lxGNQdD5RapjqzQHxwGbqmXZPRzE4H7zrwc3/rIGpDHB7OZtXWdDf1F75Ur9IhvBVr8qSBDf9gNMvk7cc4AdXsOufaR5F6QtokxG6PBrLlYcZZnUksNoAoAfZ1/4jx6aH/tLBeJXmUzjzF9+eTLyL/YB8lJMGmndrbjEX9Eu5EW8klHkYRycWv2TC8ukV1fYD+K37VgMmiIt/zfZhPNskw/r2SQPZ8lGxkkKGEjSho6ybHQQmD5ASIJCmXMEFT/vGyhxIM=
